default:
  # Weaviate settings
  weaviate:
    url: "http://weaviate:8080"
    vector_index_config:
      distance: "cosine"
      efConstruction: 128
      maxConnections: 64
    batch_size: 100
    retry_attempts: 3
    retry_delay: 5

  # Application settings
  app:
    data_dir: "data/esco"
    log_dir: "logs"
    log_level: "INFO"
    python_unbuffered: true
    staleness_threshold_seconds: 7200
    stale_timeout_hours: 2
    ingestion_wait_timeout_minutes: 60
    ingestion_poll_interval_seconds: 30

  # Model settings
  model:
    device: "auto"  # auto, cpu, cuda, mps
    embedding_model: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
    translation_model: "Helsinki-NLP/opus-mt-en-he"
    cache_dir: "model_cache"
    batch_size: 100

  # ESCO settings (required by ingestor)
  esco:
    data_dir: "data/esco"
    batch_size: 100

cloud:
  # Weaviate settings
  weaviate:
    url: "YOUR_WEAVIATE_CLOUD_ENDPOINT_HERE"  # <-- Set your Weaviate Cloud Service endpoint here
    vector_index_config:
      distance: "cosine"
      efConstruction: 128
      maxConnections: 64
    batch_size: 100
    retry_attempts: 5
    retry_delay: 10

  # Application settings
  app:
    data_dir: "data/esco"
    log_dir: "logs"
    log_level: "INFO"
    python_unbuffered: true
    staleness_threshold_seconds: 7200
    stale_timeout_hours: 2
    ingestion_wait_timeout_minutes: 60
    ingestion_poll_interval_seconds: 30

  # Model settings
  model:
    device: "auto"  # auto, cpu, cuda, mps
    embedding_model: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
    translation_model: "Helsinki-NLP/opus-mt-en-he"
    cache_dir: "model_cache"
    batch_size: 100

  # ESCO settings (required by ingestor)
  esco:
    data_dir: "data/esco"
    batch_size: 100 